### ISSUE TITLE
Kontrol fonksiyonu sorunlu.

### ISSUE THREAD

**Issue by dispholidus** [UludagUniversitesiYazilim/XoX#1]
Fonksiyon sadece ortaya taş konduğu zaman doğru kontrol ediyor ancak kenarlara konduğu zaman hata vermekte.

**Comment by dispholidus** [comment]
Fonksiyon sadece ortaya taş konduğu zaman doğru kontrol ediyor ancak kenarlara konduğu zaman hata vermekte.

**Comment by berkayaslan** [comment]
Kenardaki ya da kosedeki elemanlarin sag sol ust gibi ozelliklerini alirken siniri asiyoruz. 3 elemanli bir listenin 4. elemanini bulmak istiyoruz. x=3 y=2 kordinatindaki bir "X" degerinin sagindaki deger x=4 y=2 oluyor ama tahtada x degeri maximum 3 oluyor. 

Her yonden deger alabilecegimiz sadece 2,2 elemani var ama onun disinda her yerin birden fazla siniri asan tarafi var. Aklima gelen bir yontem su :

Aranan elemanin nereden olduguna gore sorgu yapilsin. Ornegin sag ortadaysa sol, ust ve alt sorgulansin. Ama bunun pek bir faydasi olmaz cunku kenarda olmayan sadece 1 deger var. Fazladan kod yazariz.

Bir diger yontem;

Manual olarak kontrol etmek. Verilen elemanin sagina soluna bak ayni degerde eleman varsa onun sagina soluna bak 3 tane ardarda ayni eleman varsa oyun bitmistir.

Bir diger yontem ise her islem sonunda tum karelari kontrol etmek.

Ama bu fonksiyonu silmek dogru olmaz. Cunku eger SOS olarak guncelleyeceksek bu algoritma cok daha pratik olur. Cunku SOS tahtasinda kenardan cok orta eleman var.
