### ISSUE TITLE
GUI'de üst üste binme problemi

### ISSUE THREAD

**Issue by berkayaslan** [UludagUniversitesiYazilim/XoX#2]
Gui uygulamasında X ya da O ile işaretlenmiş kutuların kilitlenmesi ve oyun sonuna kadar basılmaması gerekiyor. Ancak şu anda Kolayca basılabiliniyor.

**Comment by dispholidus** [comment]
Artık dolu kareye tekrar hamle yapılmaya çalışırsa ayrı küçük bir pencerede uyarı veriyor.
