### ISSUE TITLE
Hata ve Uyarı Mesajları Konumu

### ISSUE THREAD

**Issue by berkayaslan** [UludagUniversitesiYazilim/XoX#8]
Hata ve uyarı mesajları windows işletim sisteminde Tam ortada çıkıyor. Ancak tam orta nokta pencereye uzak kalıyor. Pencere ortaya alınmalı ya da hata mesaj pencereleri düzenlenmeli.

**Comment by berkayaslan** [comment]
Pencere ortaya konuldu ancak Windows sistemlerinde denemedim. Birinizin denemesi ve burada bildirmesi gerekiyor. @dispholidus @osmnbrk

**Comment by dispholidus** [comment]
sorun yok.
